### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by yulric** [Big-Life-Lab/local-transformations-generator#3]
## Features

* [ ] Mutation inside if blocks
* [ ] z-scoring inside functions
* [ ] If a source function call throws an error that it can't find the file, we should throw the error to the user

## Refactors

* [ ] Remove duplicate code for generating PMML for is expressions inside the define-function and derived-field functions
* [ ] Remove duplicate code for generating inner function names within the define-function module
